sudo: false
language: python
branches:
  only:
    - master
python:
  - "3.4"
install:
  - "git fetch --unshallow"
  - "python bootstrap.py --setuptools-version=12.0.4"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/buildout -c buildout-${BUILDOUT_TARGET}.cfg 2>/dev/null"
script:
  - "./bin/ad_check_code -a"
  - "./bin/polytester -v pyunit,pyfunc,jsunit"
  - "PATH=${TRAVIS_BUILD_DIR}/bin:${PATH} ./bin/protractor etc/protractorConfSauce.js"
notifications:
  email: false
cache:
  directories:
    - eggs
    - node_modules
addons:
  sauce_connect: true
env:
  matrix:
    - BUILDOUT_TARGET=meinberlin
    - BUILDOUT_TARGET=mercator
    - BUILDOUT_TARGET=spd
  global: # SAUCE_USERNAME and SAUCE_ACCESS_KEY
    - secure: ovz89AOVSOa0HefNp4Wbl1t5jV6nTJqQhf99klH/FAEtQRsZe5oklzi0zpDUXa1zIF18pGFLt0Bv8Nct7njp0N2fH8oItP7jmHpGwhHE8EQTWdvMq7KK3UX30JdXrFsyHTxnW8nGlNdTRcww/zn7KjwUTbja+4Y0RsCBB5HdA+w=
    - secure: jBR7/2APY1qskecsyPsTcxogGeS3xuPXwFM2SnS70hKfsdWOt0SCrJC5MpjAqmUHWnPh4g8rTT6uX/JyfBOgEh7ny1matjHsm+dwlDW/Y3QA73RuxU+KXVgXVg3YUlYFCQT7Ttx9Xj3qp5j0BrvZelGYLI3rSjvNRFW2bKsBQYg=
after_success:
  - ./bin/coveralls
