sudo: false
language: python
python:
  - "3.4"
install:
  - "python bootstrap.py --setuptools-version=12.0.4"
  - "PATH=${PATH}/bin ./bin/buildout 2>/dev/null"
script:
  - "./bin/py.test_run_unittests_with_coverage"
  - "./bin/py.test_run_all"
  - "./bin/protractor etc/protractorConfSauce.js"
git:
  depth: 3000
notifications:
  email: false
after_success:
  - "./bin/coveralls"
cache:
  directories:
    - eggs
    - node_modules
addons:
  sauce_connect: true
env:
  global:
  # SAUCE_USERNAME
  - secure: ovz89AOVSOa0HefNp4Wbl1t5jV6nTJqQhf99klH/FAEtQRsZe5oklzi0zpDUXa1zIF18pGFLt0Bv8Nct7njp0N2fH8oItP7jmHpGwhHE8EQTWdvMq7KK3UX30JdXrFsyHTxnW8nGlNdTRcww/zn7KjwUTbja+4Y0RsCBB5HdA+w=
  # SAUCE_ACCESS_KEY
  - secure: Nt4lAAiTCqTGBj7nPu+Kov1MeFUaapI4swkyoDHsXGE2x6/aeDmOErOHrur5QrOQEOkqwsLPeeshuu4J+3+f3LdhnV0kRVkNMRryFqOM4I953jhgsw8B+p4KWT7/sqCT2ubCmyVcaLjNlDX+pdZIu2pT9LcEkF8tfg5zkDcf5Fw=
